load 'deploy' if respond_to?(:namespace) # cap2 differentiator
Dir['vendor/plugins/*/recipes/*.rb'].each { |plugin| load(plugin) }

load 'app/config/deploy'
# require 'rubygems'
# require 'railsless-deploy'